import Head from 'next/head'
import Body from 'components/landing-body'
import Navbar from 'components/landing-navbar'
import { useState } from 'react'

export default function Home() {

  const [login, setLogin] = useState("Home")

  function handleLogin(state){
    setLogin(state)
  }

  return (
    <div className="">
      <Head>
        <title>Questions App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar handleLogin={handleLogin}/>
      <Body login={login} handleLogin={handleLogin}/>
    </div>
  )
}
