import Head from 'next/head'

import FormCreationInterface from 'components/form-creation-interface'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Questions App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FormCreationInterface />
    </div>
  )
}
